# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Programming\Python\OrderImport\FileViewerApp\ManageSKUs.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManageSKUsDialog(object):
    def setupUi(self, ManageSKUsDialog):
        ManageSKUsDialog.setObjectName("ManageSKUsDialog")
        ManageSKUsDialog.resize(545, 536)
        self.verticalLayoutWidget = QtWidgets.QWidget(ManageSKUsDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 9, 511, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tvwItems = QtWidgets.QTableView(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tvwItems.sizePolicy().hasHeightForWidth())
        self.tvwItems.setSizePolicy(sizePolicy)
        self.tvwItems.setObjectName("tvwItems")
        self.verticalLayout.addWidget(self.tvwItems)
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 250))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 481, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.txtCustomerSKU = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtCustomerSKU.setText("")
        self.txtCustomerSKU.setObjectName("txtCustomerSKU")
        self.gridLayout.addWidget(self.txtCustomerSKU, 2, 1, 1, 1)
        self.cbCustomer = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbCustomer.setObjectName("cbCustomer")
        self.gridLayout.addWidget(self.cbCustomer, 0, 1, 1, 1)
        self.cbDefySKU = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbDefySKU.setObjectName("cbDefySKU")
        self.gridLayout.addWidget(self.cbDefySKU, 3, 1, 1, 1)
        self.btnRefreshSKU = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnRefreshSKU.setObjectName("btnRefreshSKU")
        self.gridLayout.addWidget(self.btnRefreshSKU, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAdd = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.btnSave = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnSave.setEnabled(False)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_2.addWidget(self.btnSave)
        self.btnCancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnCancel.setEnabled(False)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)
        self.btnDelete = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnDelete.setEnabled(False)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout_2.addWidget(self.btnDelete)
        self.btnClose = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_2.addWidget(self.btnClose)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ManageSKUsDialog)
        self.btnClose.clicked.connect(ManageSKUsDialog.close)
        QtCore.QMetaObject.connectSlotsByName(ManageSKUsDialog)
        ManageSKUsDialog.setTabOrder(self.tvwItems, self.cbCustomer)
        ManageSKUsDialog.setTabOrder(self.cbCustomer, self.txtCustomerSKU)
        ManageSKUsDialog.setTabOrder(self.txtCustomerSKU, self.cbDefySKU)
        ManageSKUsDialog.setTabOrder(self.cbDefySKU, self.btnAdd)
        ManageSKUsDialog.setTabOrder(self.btnAdd, self.btnSave)
        ManageSKUsDialog.setTabOrder(self.btnSave, self.btnCancel)
        ManageSKUsDialog.setTabOrder(self.btnCancel, self.btnDelete)
        ManageSKUsDialog.setTabOrder(self.btnDelete, self.btnClose)
        ManageSKUsDialog.setTabOrder(self.btnClose, self.btnRefreshSKU)

    def retranslateUi(self, ManageSKUsDialog):
        _translate = QtCore.QCoreApplication.translate
        ManageSKUsDialog.setWindowTitle(_translate("ManageSKUsDialog", "Manage SKUs"))
        self.groupBox.setTitle(_translate("ManageSKUsDialog", "SKU Data"))
        self.label_5.setText(_translate("ManageSKUsDialog", "Defy SKU"))
        self.label.setText(_translate("ManageSKUsDialog", "Customer SKU"))
        self.label_2.setText(_translate("ManageSKUsDialog", "Customer Name"))
        self.btnRefreshSKU.setText(_translate("ManageSKUsDialog", "Refresh SKUs"))
        self.btnAdd.setText(_translate("ManageSKUsDialog", "Add"))
        self.btnSave.setText(_translate("ManageSKUsDialog", "Save"))
        self.btnCancel.setText(_translate("ManageSKUsDialog", "Cancel"))
        self.btnDelete.setText(_translate("ManageSKUsDialog", "Delete"))
        self.btnClose.setText(_translate("ManageSKUsDialog", "Close"))
