# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Programming\Python\OrderImport\FileViewerApp\ManageBranches.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManageBranchesDialog(object):
    def setupUi(self, ManageBranchesDialog):
        ManageBranchesDialog.setObjectName("ManageBranchesDialog")
        ManageBranchesDialog.resize(545, 464)
        self.verticalLayoutWidget = QtWidgets.QWidget(ManageBranchesDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 9, 511, 441))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tvwItems = QtWidgets.QTableView(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tvwItems.sizePolicy().hasHeightForWidth())
        self.tvwItems.setSizePolicy(sizePolicy)
        self.tvwItems.setObjectName("tvwItems")
        self.verticalLayout.addWidget(self.tvwItems)
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 180))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 481, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.txtDefyBranchCode = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtDefyBranchCode.setText("")
        self.txtDefyBranchCode.setObjectName("txtDefyBranchCode")
        self.gridLayout.addWidget(self.txtDefyBranchCode, 3, 2, 1, 1)
        self.cb = QtWidgets.QLabel(self.gridLayoutWidget)
        self.cb.setObjectName("cb")
        self.gridLayout.addWidget(self.cb, 0, 0, 1, 1)
        self.txtCustBranchCode = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtCustBranchCode.setText("")
        self.txtCustBranchCode.setObjectName("txtCustBranchCode")
        self.gridLayout.addWidget(self.txtCustBranchCode, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.cbCustomer = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbCustomer.setObjectName("cbCustomer")
        self.gridLayout.addWidget(self.cbCustomer, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnAdd = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout_2.addWidget(self.btnAdd)
        self.btnSave = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnSave.setEnabled(False)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_2.addWidget(self.btnSave)
        self.btnCancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnCancel.setEnabled(False)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)
        self.btnDelete = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnDelete.setEnabled(False)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout_2.addWidget(self.btnDelete)
        self.btnClose = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout_2.addWidget(self.btnClose)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ManageBranchesDialog)
        self.btnClose.clicked.connect(ManageBranchesDialog.close)
        QtCore.QMetaObject.connectSlotsByName(ManageBranchesDialog)
        ManageBranchesDialog.setTabOrder(self.tvwItems, self.cbCustomer)
        ManageBranchesDialog.setTabOrder(self.cbCustomer, self.txtCustBranchCode)
        ManageBranchesDialog.setTabOrder(self.txtCustBranchCode, self.txtDefyBranchCode)
        ManageBranchesDialog.setTabOrder(self.txtDefyBranchCode, self.btnAdd)
        ManageBranchesDialog.setTabOrder(self.btnAdd, self.btnSave)
        ManageBranchesDialog.setTabOrder(self.btnSave, self.btnCancel)
        ManageBranchesDialog.setTabOrder(self.btnCancel, self.btnDelete)
        ManageBranchesDialog.setTabOrder(self.btnDelete, self.btnClose)

    def retranslateUi(self, ManageBranchesDialog):
        _translate = QtCore.QCoreApplication.translate
        ManageBranchesDialog.setWindowTitle(_translate("ManageBranchesDialog", "Manage Branches"))
        self.groupBox.setTitle(_translate("ManageBranchesDialog", "Branch Data"))
        self.label_5.setText(_translate("ManageBranchesDialog", "Defy Branch Code"))
        self.cb.setText(_translate("ManageBranchesDialog", "Select Customer"))
        self.label.setText(_translate("ManageBranchesDialog", "Customer Branch Code"))
        self.btnAdd.setText(_translate("ManageBranchesDialog", "Add"))
        self.btnSave.setText(_translate("ManageBranchesDialog", "Save"))
        self.btnCancel.setText(_translate("ManageBranchesDialog", "Cancel"))
        self.btnDelete.setText(_translate("ManageBranchesDialog", "Delete"))
        self.btnClose.setText(_translate("ManageBranchesDialog", "Close"))
